version: 2
jobs:
  build:
    working_directory: ~/circleci-image

    docker:
      - image: circleci/openjdk:11-jdk

    steps:

      - checkout

      - run:
          name: Make gradlew executable
          command: |
            sudo chmod +x gradlew
            systemctl start docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew clean build integrationTest docker

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - store_artifacts:
          path: build/libs/image-0.0.1-SNAPSHOT.jar