version: 2
jobs:
  build:
    working_directory: ~/circleci-image

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradlew clean build integrationTest

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/libs/image-0.0.1-SNAPSHOT.jar